/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/bindings.d.ts` (hash: 5fba76ea2db58603ef4d50237624e47f)
interface __BaseEnv_Env {
	FLAGS: Flagship;
	ASSETS: Fetcher;
	OIDC_ISSUER: string;
	OIDC_CLIENT_ID: string;
	OIDC_CLIENT_SECRET: string;
	OIDC_RESOURCE: string;
	OIDC_SESSION_SECRET: string;
	ENVIRONMENT: string;
	ROOM: DurableObjectNamespace<import("./index").RoomDurableObject>;
	REPLAY: DurableObjectNamespace<import("./index").ReplayDurableObject>;
	ACCOUNT_PROFILE: DurableObjectNamespace<import("./index").AccountProfileDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RoomDurableObject" | "ReplayDurableObject" | "AccountProfileDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
